const request = require('supertest');
const session = require('./session')();
const { assert, expect } = require('chai');

module.exports = app => {
    describe('Documents CRUD should be working', function() {
        const documentSent = { 
            name: 'some-doc',
            description: 'some-description',
            category: 'test',
            doc: `some-pdf-dataBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowOD`
        };

        const documentSent2 = { 
            name: 'some-doc2',
            description: 'some-description2',
            category: 'some-test2',
            doc: `
            some-pdf-dataBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowODBQABAAAA+gAAABwBAwABAAAAAQAAACgBAwABAAAAAgAAADEBAgALAAAAAgEAADIBAgAUAAAADgEAAGmHBAABAAAAIgEAAP4CAAAIAAgACABDYW5vbgBDYW5vbiBFT1MtMURzIE1hcmsgSUlJAACA/AoAECcAAID8CgAQJwAAUGljYXNhIDMuMAAAMjAwODowOD`
        };

        it("Create", done => {
            request(app)
                .post('/cms/documents/')
                .send(documentSent)
                .set('Accept', 'application/json')
                .set('Auth-Token', session.user.token)
                .expect(200)
                .end(function(err, res) {
                    if (err) throw err;
                    request(app)
                        .post('/cms/documents/')
                        .send(documentSent)
                        .set('Accept', 'application/json')
                        .set('Auth-Token', session.user.token)
                        .expect(200)
                        .end(function(err, res) {
                            if (err) throw err;
                            done();
                        });
                });
        });

        it("Retrieve", done => {
            request(app)
                .get('/cms/documents/')
                .set('Accept', 'application/json')
                .set('Auth-Token', session.user.token)
                .expect(200)
                .end(function(err, res) {
                    if (err) throw err;
                    const documents = res.body;
                    expect(documents).to.not.be.eql(undefined);
                    const document = documents.reverse().pop();
                    expect(document).to.not.be.eql(null);
                    assert(document.name, documentSent.name);
                    assert(document.description, documentSent.description);
                    assert(document.category, documentSent.category);
                    documentSent.id = document.id;
                    done();
                });
        });

        it("Update", done => {
            documentSent.name = documentSent2.name;
            documentSent.description = documentSent2.description;
            documentSent.category = documentSent2.category;
            documentSent.doc = documentSent2.doc;
            request(app)
                .put(`/cms/documents/${documentSent.id}`)
                .send(documentSent)
                .set('Accept', 'application/json')
                .set('Auth-Token', session.user.token)
                .expect(200)
                .end(function(err, res) {
                    if (err) throw err;
                    done();
                });
        });

        it("Check update", done => {
            request(app)
                .get(`/cms/documents/id/${documentSent.id}`)
                .set('Accept', 'application/json')
                .set('Auth-Token', session.user.token)
                .expect(200)
                .end(function(err, res) {
                    if (err) throw err;
                    const document = res.body;
                    expect(document).to.not.be.eql(null);
                    assert(document.name, documentSent.name);
                    assert(document.description, documentSent.description);
                    assert(document.category, documentSent.category);
                    assert(document.doc, documentSent.doc);
                    done();
                });
        });

        it("Delete", done => {
            request(app)
                .delete(`/cms/documents/${documentSent.id}`)
                .set('Accept', 'application/json')
                .set('Auth-Token', session.user.token)
                .expect(200)
                .end(function(err, res) {
                    if (err) throw err;
                    done();
                });
        });

        it("Check deletion", done => {
            request(app)
                .get('/cms/documents/')
                .set('Accept', 'application/json')
                .set('Auth-Token', session.user.token)
                .expect(200)
                .end(function(err, res) {
                    if (err) throw err;
                    const documents = res.body;
                    expect(documents.length).to.be.eql(1);
                    done();
                });
        });
    });
}

